In [3]:
import numpy as np
import pandas as pd
import statistics as st


In [47]:
def read(name,lname, sname):
    return pd.read_excel(name,index_col=0,usecols=lname,sheet_name=sname)

In [59]:
purchase_data = read("Lab Session Data.xlsx", [0,1,2,3,4],"Purchase data")
col = purchase_data.columns
table1b = purchase_data.to_numpy()
A = purchase_data[[col[0],col[1],col[2]]].to_numpy()
C = purchase_data[col[3]].to_numpy()

print(purchase_data)
print(f"Dimension of data: {table1b.shape}")
print(f"Number of Vectors: {table1b.shape[0]}")
print(f"Rank of Matrix A: {np.linalg.matrix_rank(A)}")

X = np.linalg.pinv(A) @ C
print(f"Matrix X: {X}")



[[ 20   6   2 386]
 [ 16   3   6 289]
 [ 27   6   2 393]
 [ 19   1   2 110]
 [ 24   4   2 280]
 [ 22   1   5 167]
 [ 15   4   2 271]
 [ 18   4   2 274]
 [ 21   1   4 148]
 [ 16   2   4 198]]
Dimension of data: (10, 4)
Number of Vectors: 10
Rank of Matrix A: 3
Matrix X: [ 1. 55. 18.]


In [62]:
X = np.linalg.pinv(A) @ C
print(f"Matrix X: {X}")

Matrix X: [ 1. 55. 18.]


In [64]:
def classify(payment):
    if payment >= 200:
        return 'RICH'
    else:
        return 'POOR'

classifier = np.vectorize(classify)
customer = classifier(C)
purchase_data['class'] = customer
print(purchase_data)

          Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs) class
Customer                                                                 
C_1                20             6                 2           386  RICH
C_2                16             3                 6           289  RICH
C_3                27             6                 2           393  RICH
C_4                19             1                 2           110  POOR
C_5                24             4                 2           280  RICH
C_6                22             1                 5           167  POOR
C_7                15             4                 2           271  RICH
C_8                18             4                 2           274  RICH
C_9                21             1                 4           148  POOR
C_10               16             2                 4           198  POOR


In [78]:
irctc_data = read("Lab Session Data.xlsx", [0,1,2,3,4,5,6,7,8],"IRCTC Stock Price")
price = irctc_data['Price'].to_numpy()
population_mean = np.mean(price)
population_variance = np.var(price)
print(f"Mean: {population_mean}")
print(f"Variance: {population_variance}")

wednesday_mean = np.mean(irctc_data[irctc_data['Day'] == 'Wed']['Price'].to_numpy())
print(f"Mean of stock price on Wednesday: {population_mean == wednesday_mean}")
print(f"Comparison: {population_mean == wednesday_mean}")

april_mean = np.mean(irctc_data[irctc_data['Month'] == 'Apr']['Price'].to_numpy())
print(f"Mean of stock price in April {april_mean}")

change = irctc_data['Chg%'].to_numpy()
loss_change = irctc_data[irctc_data['Chg%']<0]['Chg%'].to_numpy()
probability_loss = len(loss_change)
print(f"Probability of making a loss over the stock")

Mean: 1560.6634538152612
Variance: 58496.49239931613
Comparison: False
